# Promise
> [Promise 项目实践与异常处理方式](https://blog.csdn.net/billll/article/details/74081426)

## 概念
> Promise对象是一个代理对象，它允许你为异步操作的成功和失败分别绑定相应的处理方法。

## 流程
> promise实例化->then->状态就绪->调用resolve或reject->done结束->handle->改变状态onfullfiled/onrejected

## 异常处理
> 我们可以在reject回调和catch中处理异常，如果一个错误在reject函数中被处理，那么promise将从异常态中恢复过来。这意味着接下来的then方法会收到一个resolve回调，但我们希望发生错误的时候，promise处理当前的异常并终端后续的then操作。

## 手写一个Promise
```javascript
   function myPromise(constructor) {
       let self = this;
       self = {
           status: 'pending',
           value: undefined,
           reason: undefined,
       }
       function resolve(value) {
           if(self.status === 'pending') {
               self.value = value
               self.status = 'resolved'
           }
       }
       function rejected(reason) {
           if(self.status === 'pending') {
               self.reason = reason
               self.status = 'rejected'
           }
       }
       try {
        // 捕获构造异常
           constructor(resolve, reject )
       } catch(e) {
           reject(e)
       }
   }
   myPromise.prototype.then = function(onFullfilled, onRejected) {
       let self = this
       switch(self.status) {
           case 'resolved':
             onFullfilled(self.value)
             break;
           case 'rejected':
             onRejected(self.value)
             break;
            default:
       }
   }
```
